language: node_js
node_js:
- 6.9.1
cache:
  directories:
  - ~/.nvm
  - node_modules
git:
  depth: 1
env:
  global:
  - RELEASE_BRANCH="master"
  - MAIN_BRANCHES="master develop"
  - secure: hP2jQ+Jt+J8ELRFTuGP0HfApQL0wJ18xdy2uQ03s8++pvz15CIV3fNc8cGJARjp0qWyDPxNt/Y7fwOD98yoD+vGfXGwy2kwe6Fo5cLBEbeZK7f3E3Ioej+4SbZNJXlAAvLWTbISMgnYGxcJ/V7NEV3Kf8T2o0gOIOQZzmork2IVwhb1i4Z3TO5/O9iSRwifCEeJocAffCaunnl4kNWT9sfyKlaVCBovfwV6iYl1IwoyTrRTDQ69ziYaS1Jt4ROLRvMvDdzYZE+g9JzX4oqBzgAcdiqUSfEwkpySzVbJLAJBN9gXPhqmBZWpQ7bNuNlDYTHcD8XrF+MiZLqjD3HWWz0XowI25B6eMj60Wa0j/9gOCLxsKWALqz2OY/0M7OUcOHNNyf4jC8KlBW5IvCUk/h45517dgUwa1+zjrhFYTxQ7v9IrLv0umygonw0jx3ni7R3ckzh69+wlxrQInVHD/8LOMGvgcgWYod0qWHFXsAjQlRHK8mTfC5kqmr2c+jH//vS9OEQL7m784zH6+bXGyCZaKMW0XQTpUXsOet6CJwx54ERMrtYyP+W5ku+PGdVKZVN+j7rg6kRfe7NGzqYL85e6RoJJdKU7+FyFNuVeDssMTjRFvUbjCCkvLy1wrT8QlT8QBuHXW9rWZaighcx0kbmpWFF/OBJzxsLO57AnnNE4=
before_script:
- chmod -R +x bin
- ./bin/version-increment.sh || { exit 1; }
script:
- npm run lint && npm test || { exit 1; }
after_success:
- ./bin/ci/push.sh
deploy:
  provider: npm
  email: ivchenkodima@gmail.com
  skip_cleanup: true
  api_key:
    secure: iRaFHdyZMdtPLPJ9WbcZupq8jPkI/SV7ZaW8Z8tt5kKvFeez54HJBf0PuU1ezbBwSbULv3IyqnprivfL4quPv38mLQsNFxBQiPJrxJCz040/XFG3VHGMEPwrgOpE+dYKUjXp8iGOazTqXDqYTKNYTYojxEnRMfDUcyzv4aR0XIhuWlf63e/j6y7pXGi/t7RUiE5rlhrRYw9Aw4IbM2IcD+aXzhBIFB3OHHNIED75ZbiDKPu4OzqmliFXK3UoPhZe97Q5ot1i6gT0V8syogQOPziUxmYs/xYJShQmcoqBQEfOBb/7kCO7K8N93D6xYllqympbJY9xgdLkP25aFAB7g2QRF8YkYvpJUGFGlTWU3cJPtf3OnqNSqiaGATb2p7u8nfzM+5qvxuN5VPWFjnCjksff/9b9OUc3IYpU4puDrvQywATf+OR1Wd++F1GGztA6Gm6G08VFPdFcVPMCereyqJa+hs+A2iwPmVOHlru6zRL7u7+OYdozree6lbK4I+i9rTamhibtUkmduHa0GZyV2obh+MjHROWFrWeJ/+Amg3aWFDpZpzFkHDUPsVEspDW+a7eSw5Qv6oB8kwYo3Ry/cb1he3hExem9Yt6Ns/oUp5NUK6KMbGydd6GN6YuX/l8KUmK8IQs35hUnx4HULk/txyglik3QyVNouYwJE7qdZzU=
  on:
    branch: master
    repo: Nebo15/react-nebo15-components
