language: node_js
node_js:
- 6.9.1
cache:
  directories:
  - "~/.nvm"
  - node_modules
git:
  depth: 1
env:
  global:
  - RELEASE_BRANCH="master"
  - MAIN_BRANCHES="master develop"
  - secure: ij7ByR80GQ75cmeI3rn0/zFAgkyD9xhOUwam6zzEB2EEYlIffrr7SsZH+Nt/1znuzUMuLKJnkI16Py49qk4HS+MY088fy2LgTI8k3ypEeZ3C9yP77KR8gOc1exQtyDhyv+CO/uUWg3GGSDa1Cr1PDJWk7rL4jNNg9kwSxNlRjiruZnMJrYY8mOhPkfJz6HDmRlpToK4Eh4cvhrKy/ZySEhlrdGyNZNXUkIOCDAFXiJZgr66tZuuwN3t+sJxsKaeoEoGW82a9Yi/zSZ8Iiauf6/VAxUloZryF5PlVALJMj1eoLsdgjWPC009c64quFBN9lbF9xwhMAbyk+hby8iZBA3h/fNM08yjX3DJ6+l4yk19TC5Ngo6c4maDqV/DDhj99JrfUmNRXVdHa07uZHfA+s4Am2bp2F0RA8xrsBTsgRd7CUibNkR3wMwKb+Wc5FR2HaWRYcrqS6S/ypkzgVq/+Bf1p4SeFsmlg1zoW77q5YQisF5Xbpy6+Wuip3MT9XjwVGamOIbmj0HgR7MqH52AholwoOk8vq608E5c71FQo1/wWtUxFZUFiw36+7pnoa0yQO1bkRAyD7PKmtuWBLyKM6vJ/YNqw8imkejF236M5wZYLAfkkedrY9PCwvp40LR22ildZ5sekn6fd531UPFPalyqVdJVVtHA5Fpe3fxrssbU=
before_script:
- chmod -R +x bin
- "./bin/version-increment.sh || { exit 1; }"
script:
- npm run lint && npm test || { exit 1; }
after_success:
- "./bin/ci/push.sh"
deploy:
  provider: npm
  email: ivchenkodima@gmail.com
  skip_cleanup: true
  api_key:
    secure: FUbrKgCUAlqBGxNSMX2o//9H24U3FcOqIHMWDrfjQyIsDni4cOTKMHf0EtXXdz/tRBrasS3jeMh+rulxDvp261Z4pbn296WghH8TUDlD7I5WRCKwWvoYjXb6yAKb6ekky4yrMLexqZ/iSfnboh0qRGkcgeFl8JR1zFz0h75UNrDRZE68srIIjoJ7YW8pvzeKsfbaMe773QmiCjytD+ExpFZvH8oYwwIPgzUGR8EkMFdnREOwApi143aoI+Tbl2+f45y9HjVMtkJcS3Vjiei3EDBDCTsIR+Ebt2UC3usGMc3qK9emqjc6azZGSloiIgpLGp0vCTyyJO9ATgP6msz8NqhtcxqEh4KTJME0AnKDSRqw9zaE4OBrJhcuG14R4d0Yf0ndQOppvKg/iwho7dWvV8VebdXpq1Sg93l5SDNeLgt6gy5DQiRgXMCAJ94ipTJ3WL+PONmDPLwNlcw0tLv5Z+b5KELmkl5jEbdl1/SkduhKrMSUfitjJ0Sy+0l+fob4Yziu4aGJINncUOigVkWOb2WOuZETxQOL3YqcNZtm0hZwkvB+c4cIAmvCdaC0+rOCFKXERCQtKI8G8tUZGZNnh6AtoVZ2ETJUGBD8oxLRUD7hNvi5SaVpeM0WEguDdaukfPbZcu5a3llQ3BNpFk2ljVtbQ7Ui22nr77/9djTJKwo=
  on:
    branch: master
    repo: Nebo15/react-nebo15-components
