language: node_js
node_js:
- 6.9.1
cache:
  directories:
  - ~/.nvm
  - node_modules
git:
  depth: 1
env:
  global:
  - RELEASE_BRANCH="master"
  - MAIN_BRANCHES="master develop"
  - secure: hP2jQ+Jt+J8ELRFTuGP0HfApQL0wJ18xdy2uQ03s8++pvz15CIV3fNc8cGJARjp0qWyDPxNt/Y7fwOD98yoD+vGfXGwy2kwe6Fo5cLBEbeZK7f3E3Ioej+4SbZNJXlAAvLWTbISMgnYGxcJ/V7NEV3Kf8T2o0gOIOQZzmork2IVwhb1i4Z3TO5/O9iSRwifCEeJocAffCaunnl4kNWT9sfyKlaVCBovfwV6iYl1IwoyTrRTDQ69ziYaS1Jt4ROLRvMvDdzYZE+g9JzX4oqBzgAcdiqUSfEwkpySzVbJLAJBN9gXPhqmBZWpQ7bNuNlDYTHcD8XrF+MiZLqjD3HWWz0XowI25B6eMj60Wa0j/9gOCLxsKWALqz2OY/0M7OUcOHNNyf4jC8KlBW5IvCUk/h45517dgUwa1+zjrhFYTxQ7v9IrLv0umygonw0jx3ni7R3ckzh69+wlxrQInVHD/8LOMGvgcgWYod0qWHFXsAjQlRHK8mTfC5kqmr2c+jH//vS9OEQL7m784zH6+bXGyCZaKMW0XQTpUXsOet6CJwx54ERMrtYyP+W5ku+PGdVKZVN+j7rg6kRfe7NGzqYL85e6RoJJdKU7+FyFNuVeDssMTjRFvUbjCCkvLy1wrT8QlT8QBuHXW9rWZaighcx0kbmpWFF/OBJzxsLO57AnnNE4=
before_script:
- chmod -R +x bin
- ./bin/version-increment.sh || { exit 1; }
script:
- npm run lint && npm test || { exit 1; }
after_success:
- ./bin/ci/push.sh
deploy:
  provider: npm
  email: ivchenkodima@gmail.com
  skip_cleanup: true
  api_key:
    secure: FUbrKgCUAlqBGxNSMX2o//9H24U3FcOqIHMWDrfjQyIsDni4cOTKMHf0EtXXdz/tRBrasS3jeMh+rulxDvp261Z4pbn296WghH8TUDlD7I5WRCKwWvoYjXb6yAKb6ekky4yrMLexqZ/iSfnboh0qRGkcgeFl8JR1zFz0h75UNrDRZE68srIIjoJ7YW8pvzeKsfbaMe773QmiCjytD+ExpFZvH8oYwwIPgzUGR8EkMFdnREOwApi143aoI+Tbl2+f45y9HjVMtkJcS3Vjiei3EDBDCTsIR+Ebt2UC3usGMc3qK9emqjc6azZGSloiIgpLGp0vCTyyJO9ATgP6msz8NqhtcxqEh4KTJME0AnKDSRqw9zaE4OBrJhcuG14R4d0Yf0ndQOppvKg/iwho7dWvV8VebdXpq1Sg93l5SDNeLgt6gy5DQiRgXMCAJ94ipTJ3WL+PONmDPLwNlcw0tLv5Z+b5KELmkl5jEbdl1/SkduhKrMSUfitjJ0Sy+0l+fob4Yziu4aGJINncUOigVkWOb2WOuZETxQOL3YqcNZtm0hZwkvB+c4cIAmvCdaC0+rOCFKXERCQtKI8G8tUZGZNnh6AtoVZ2ETJUGBD8oxLRUD7hNvi5SaVpeM0WEguDdaukfPbZcu5a3llQ3BNpFk2ljVtbQ7Ui22nr77/9djTJKwo=
  on:
    branch: master
    repo: Nebo15/react-nebo15-components
